name: CI - archive

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 12

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 1.22.4

      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Download Dependencies
        run: flutter pub get

      - name: Build Android Project
        run: flutter build apk --release

      - name: Archive Android Build
        uses: actions/upload-artifact@v2
        with:
          name: Android build (zipped apk file, unsigned)
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build iOS Project
        run: |
          flutter build ios --release --no-codesign
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload
          zip -r -y Payload.zip Payload/Runner.app
          mv Payload.zip app-release.ipa

      - name: Archive iOS Build
        uses: actions/upload-artifact@v2
        with:
          name: iOS build (zipped ipa file, unsigned)
          path: app-release.ipa
